# font_family      Inconsolata Nerd Font Propo
font_size        11.0
cursor_shape     block
cursor_blink_interval     2
cursor_stop_blinking_after 0.0
mouse_hide_wait  0.0
enable_audio_bell no
confirm_os_window_close 0


# BEGIN_KITTY_FONTS
font_family      family='Inconsolata Nerd Font' postscript_name=auto
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
