Section "Device"
    Identifier "AMD GPU"
    Driver "amdgpu"
    Option "VariableRefresh" "true"
    Option "DRI" "3"
    Option "TearFree" "true"
EndSection

Section "Monitor"
    Identifier "eDP"
    Option "PreferredMode" "2560x1600"
    Option "Position" "0 0"
    Option "VariableRefresh" "true"
EndSection
